"""
Maximo Manage Integration Module
Handles service request creation in IBM Maximo Manage
"""

import os
import requests
import json
import base64
from typing import Dict, List, Optional
import logging

logger = logging.getLogger(__name__)


class MaximoClient:
    """Client for IBM Maximo Manage REST API"""
    
    def __init__(self):
        self.base_url = os.getenv('MAXIMO_URL', '').rstrip('/')
        self.api_key = os.getenv('MAXIMO_API_KEY', '')
        
        if not self.base_url or not self.api_key:
            logger.warning("Maximo credentials not configured. Service request creation will be disabled.")
            self.enabled = False
        else:
            self.enabled = True
            # Maximo REST API endpoint
            self.api_url = f"{self.base_url}/maximo/oslc/os/mxsr"
            logger.info(f"Maximo integration enabled: {self.base_url}")
    
    def _get_headers(self) -> Dict[str, str]:
        """Get HTTP headers for Maximo API requests"""
        return {
            'Content-Type': 'application/json',
            'apikey': self.api_key,
            'Accept': 'application/json'
        }
    
    def create_service_request(
        self,
        description: str,
        location: str,
        priority: int = 2,
        details: str = "",
        reported_by: str = "POTHOLE_ANALYZER"
    ) -> Optional[Dict]:
        """
        Create a service request in Maximo Manage
        
        Args:
            description: Short description of the issue
            location: Location where the issue was found
            priority: Priority level (1=High, 2=Medium, 3=Low)
            details: Detailed description with analysis results
            reported_by: Who reported the issue
            
        Returns:
            Dict with SR details if successful, None otherwise
        """
        if not self.enabled:
            logger.error("Maximo integration not enabled. Check credentials.")
            return None
        
        try:
            # Prepare service request payload
            payload = {
                "description": description[:100],  # Maximo typically limits to 100 chars
                "description_longdescription": details,
                "location": location,
                "reportedby": reported_by,
                "reportedpriority": priority,
                "status": "NEW",
                "ticketid": None  # Auto-generated by Maximo
            }
            
            logger.info(f"Creating service request in Maximo: {description}")
            
            # Make API request
            response = requests.post(
                self.api_url,
                headers=self._get_headers(),
                json=payload,
                timeout=30
            )
            
            if response.status_code in [200, 201]:
                sr_data = response.json()
                ticket_id = sr_data.get('ticketid', 'Unknown')
                logger.info(f"Service request created successfully: {ticket_id}")
                return {
                    'success': True,
                    'ticket_id': ticket_id,
                    'href': sr_data.get('href', ''),
                    'message': f"Service request {ticket_id} created successfully"
                }
            else:
                logger.error(f"Failed to create SR. Status: {response.status_code}, Response: {response.text}")
                return {
                    'success': False,
                    'error': f"Maximo API error: {response.status_code}",
                    'message': response.text
                }
                
        except requests.exceptions.Timeout:
            logger.error("Maximo API request timed out")
            return {
                'success': False,
                'error': 'Request timeout',
                'message': 'Connection to Maximo timed out'
            }
        except Exception as e:
            logger.error(f"Error creating service request: {str(e)}")
            return {
                'success': False,
                'error': str(e),
                'message': f'Failed to create service request: {str(e)}'
            }
    
    def attach_file_to_sr(
        self,
        ticket_id: str,
        file_path: str,
        description: str = "Pothole Analysis"
    ) -> bool:
        """
        Attach a file to an existing service request
        
        Args:
            ticket_id: The service request ticket ID
            file_path: Path to the file to attach
            description: Description of the attachment
            
        Returns:
            True if successful, False otherwise
        """
        if not self.enabled:
            return False
        
        try:
            # Read file and encode as base64
            with open(file_path, 'rb') as f:
                file_data = base64.b64encode(f.read()).decode('utf-8')
            
            file_name = os.path.basename(file_path)
            
            # Maximo doclinks endpoint
            doclinks_url = f"{self.base_url}/maximo/oslc/os/mxsr/{ticket_id}/doclinks"
            
            payload = {
                "document": file_name,
                "description": description,
                "urltype": "FILE",
                "upload": True,
                "docinfoid": None,
                "document_data": file_data
            }
            
            response = requests.post(
                doclinks_url,
                headers=self._get_headers(),
                json=payload,
                timeout=60
            )
            
            if response.status_code in [200, 201]:
                logger.info(f"File attached to SR {ticket_id}: {file_name}")
                return True
            else:
                logger.error(f"Failed to attach file. Status: {response.status_code}")
                return False
                
        except Exception as e:
            logger.error(f"Error attaching file: {str(e)}")
            return False


def create_sr_from_analysis(
    summary: str,
    pothole_count: int,
    location: str = "Unknown Location",
    video_path: Optional[str] = None,
    frame_paths: Optional[List[str]] = None
) -> Optional[Dict]:
    """
    Create a service request from pothole analysis results
    
    Args:
        summary: Analysis summary text
        pothole_count: Number of potholes detected
        location: Location where video was taken
        video_path: Path to analyzed video (optional)
        frame_paths: List of paths to pothole frame images (optional)
        
    Returns:
        Dict with SR creation result
    """
    client = MaximoClient()
    
    if not client.enabled:
        return {
            'success': False,
            'error': 'Maximo integration not configured',
            'message': 'Please configure MAXIMO_URL and MAXIMO_API_KEY environment variables'
        }
    
    # Determine priority based on pothole count
    if pothole_count >= 5:
        priority = 1  # High
    elif pothole_count >= 2:
        priority = 2  # Medium
    else:
        priority = 3  # Low
    
    # Create description
    description = f"Road Maintenance Required - {pothole_count} Pothole(s) Detected"
    
    # Create detailed description
    details = f"""AUTOMATED POTHOLE DETECTION REPORT

{summary}

Location: {location}
Detection Method: AI Video Analysis (watsonx.ai)
Priority: {'High' if priority == 1 else 'Medium' if priority == 2 else 'Low'}

This service request was automatically generated by the Pothole Video Analyzer.
Please review attached images and video for detailed assessment.
"""
    
    # Create service request
    result = client.create_service_request(
        description=description,
        location=location,
        priority=priority,
        details=details
    )
    
    if result and result.get('success'):
        ticket_id = result.get('ticket_id')
        
        # Attach video if provided
        if video_path and os.path.exists(video_path):
            logger.info(f"Attaching video to SR {ticket_id}")
            client.attach_file_to_sr(ticket_id, video_path, "Analyzed Video")
        
        # Attach frame images if provided
        if frame_paths:
            for i, frame_path in enumerate(frame_paths[:5], 1):  # Limit to 5 images
                if os.path.exists(frame_path):
                    logger.info(f"Attaching frame {i} to SR {ticket_id}")
                    client.attach_file_to_sr(
                        ticket_id,
                        frame_path,
                        f"Pothole Detection Frame {i}"
                    )
    
    return result

# Made with Bob
